### ISSUE TITLE
Connection string of SQLite database

### ISSUE THREAD

**Issue by jufickel** [casbin-rs/diesel-adapter#52] opened 2020-11-29 07:26 UTC
Hi, I am trying to use diesel-adapter with a SQlite database (`casbin.sqlite`). Unfortunately I am not able to get it to work.

This is my code:
```
let database_url = std::env::var("CASBIN_DB_URL").expect("CASBIN_DB_URL must be set");
let a = DieselAdapter::new(database_url, 4).unwrap();
```
`CASBIN_DB_URL` is set to `./casbin.sqlite`.

This results in the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AdapterError(AdapterError(PoolError(Error(Some("missing \"=\" after \"./casbin.sqlite\" in connection info string\n")))))
```

I do understand that a `=` is expected but why and what comes afterwards?

I already use diesel to successfully connect to my application's database. It is happy with the simple path `./myApplication.sql`.

**Comment by hsluoyz** [comment] 2020-11-29 11:25
@GopherJ @hackerchai

**Comment by hsluoyz** [comment] 2020-11-30 01:05
Background for this issue: https://github.com/zupzup/rust-casbin-example/issues/1

**Comment by GopherJ** [comment] 2020-12-06 12:26
@jufickel Hi, sorry to be late, are you on windows? I cannot reproduce this on linux

**Comment by jufickel** [comment] 2020-12-06 18:41
@GopherJ hi, no problem. I'm working with Linux.

**Comment by hsluoyz** [comment] 2020-12-18 01:46
@jufickel can you provide detailed Rust version and OS distribution and version?

**Comment by GopherJ** [comment] 2020-12-19 17:32
diesel-adapter uses the same connection manager with diesel, https://github.com/casbin-rs/diesel-adapter/blob/master/src/adapter.rs#L27,  so normally if the url works for diesel then it should works for diesel-adapter.

**Comment by jufickel** [comment] 2020-12-19 18:55
@hsluoyz its rust 1.48.0 and ArchLinux (rolling release).

**Comment by hsluoyz** [comment] 2020-12-20 03:36
@MATRIXKOO can you take a look at this issue?

**Comment by MATRIXKOO** [comment] 2020-12-20 06:05
I have a try.

**Comment by hsluoyz** [comment] 2020-12-20 09:37
@jufickel can you provide a minimized reproducible example (maybe a github repo) ?

**Comment by jufickel** [comment] 2020-12-20 09:43
@hsluoyz the code snippet at the beginning of this issue should suffice to reproduce the behaviour.
Currently I've implemented another solution (the suggestion of zuzup). As I have not that much time for this project right now I leave it to you to further investigate the problem or to close this issue as not reproducible. Thank you anyway!

**Comment by MATRIXKOO** [comment] 2020-12-20 13:11
I can't reproduce too.

**Comment by hsluoyz** [comment] 2020-12-20 13:50
OK. I will close it for now. Feel free to open a new one as it appears again.

**Closed by hsluoyz** 2020-12-20 13:50 UTC
Labels: cannot reproduce
